---
# tasks file for update_domain_computer
- name: update the domain state
  win_domain_computer:
    state: present
    name: "{{ ansible_facts['ansible_nodename'] }}"
    dns_hostname: 
    ou: "{{ ad_ou_path }}"
    domain_admin_user: "{{ ad_domain_username }}"
    domain_admin_password: "{{ ad_domain_password }}"
    dns_domain_name: "{{ ad_domain_name }}"
  register: domain_state
  when: ad_computer_state == "present"

- debug:
    msg: "{{ domain_state }}"
