---
# tasks file for remove_domain_computer
- name: update the domain state
  win_domain_membership:
    state: "{{ ad_computer_state }}"
    domain_ou_path: "{{ ad_ou_path }}"
    domain_admin_user: "{{ ad_domain_username }}"
    domain_admin_password: "{{ ad_domain_password }}"
    dns_domain_name: "{{ ad_domain_server }}"
  register: domain_state

- win_reboot:
  when: domain_state.reboot_required
