---
# tasks file for update_domain_computer
- name: Query the domain state
  win_domain_membership:
    domain_admin_user: "{{ ad_domain_username }}"
    domain_admin_password: "{{ ad_domain_password }}"
    dns_domain_name: "{{ ad_domain_name }}"
  register: domain_state

- debug:
    msg: "{{ domain_state }}"