---
# tasks file for update_domain_computer
- name: update the domain state
  win_domain_membership:
    state: "{{ ad_computer_state }}"
    domain_admin_user: "{{ ad_domain_username }}"
    domain_admin_password: "{{ ad_domain_password }}"
    dns_domain_name: "{{ ad_domain_name }}"
    ou: "{{ ad_domain_ou.ad_domain_name }}"
  register: domain_state
  when: ad_computer_state == "domain"

- debug:
    msg: "{{ domain_state }}"

- name: remove from the domain
  win_domain_membership:
    state: "{{ ad_computer_state }}"
    workgroup_name: "WORKGROUP"
    domain_admin_user: "{{ ad_domain_username }}"
    domain_admin_password: "{{ ad_domain_password }}"
    dns_domain_name: "{{ ad_domain_name }}"
  register: domain_state
  when: ad_computer_state == "workgroup"
