---
# tasks file for remove_domain_computer
- name: remove from domain
  win_domain_membership:
    workgroup_name: WORKGROUP
    state: "{{ ad_computer_state }}"
    domain_admin_user: "{{ ad_domain_username }}"
    domain_admin_password: "{{ ad_domain_password }}"
    dns_domain_name: "{{ ad_domain_server }}"
  register: domain_state

#- win_reboot:
#  when: domain_state.reboot_required
